config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index"#,
      # :protocol => (Rails.env == "production" ? "https://" : "http://")

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#new"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      get 'supporters'
    end
    post "/stories/fetch_url_title", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :require_logged_in_user_or_400,
    :only => [ :upvote, :downvote, :unvote, :hide, :unhide, :preview ]

  before_filter :require_logged_in_user, :only => [ :destroy, :create, :edit,
    :fetch_url_title, :new ]

  before_filter :find_user_story, :only => [ :destroy, :edit, :undelete,
    :update ]

  def create
    @title = "Post Idea"
    @cur_url = "/stories/new"

    @story = Story.new(story_params)
    @story.user_id = @user.id

    if @story.valid? && !(@story.already_posted_story && !@story.seen_previous)
      if @story.save
        Countinual.count!("#{Rails.application.shortname}.stories.submitted",
          "+1")

        return redirect_to @story.comments_url
      end
    end

    return render :action => "new"
  end

  def destroy
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = true
    @story.editor = @user

    if params[:reason].present? && @story.user_id != @user.id
      @story.moderation_reason = params[:reason]
    end

    @story.save(:validate => false)

    redirect_to @story.comments_url
  end

  def edit
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @title = "Edit Story"

    if @story.merged_into_story
      @story.merge_story_short_id = @story.merged_into_story.short_id
    end
  end

  def fetch_url_title
    s = Story.new
    s.url = params[:fetch_url]

    if (title = s.fetched_title(request.remote_ip)).present?
      return render :json => { :title => title }
    else
      return render :json => "error"
    end
  end

  def new
    @title = "Post Idea"
    @cur_url = "/stories/new"

    @story = Story.new

    if params[:url].present?
      @story.url = params[:url]

      if s = Story.find_similar_by_url(@story.url)
        if s.is_recent?
          # user won't be able to submit this story as new, so just redirect
          # them to the previous story
          flash[:success] = "This URL has already been submitted recently."
          return redirect_to s.comments_url
        else
          # user will see a warning like with preview screen
          @story.already_posted_story = s
        end
      end

      if params[:title].present?
        @story.title = params[:title]
      end
    end
  end

  def preview
    @story = Story.new(story_params)
    @story.user_id = @user.id
    @story.previewing = true

    @story.vote = 1
    @story.upvotes = 1

    @story.valid?

    @story.seen_previous = true

    return render :action => "new", :layout => false
  end

  def show
    @story = Story.where(:short_id => params[:id]).first!

    if @story.merged_into_story
      flash[:success] = "\"#{@story.title}\" has been merged into this story."
      return redirect_to @story.merged_into_story.comments_url
    end

    if @story.can_be_seen_by_user?(@user)
      @title = @story.title
    else
      @title = "[Story removed]"
    end

    @short_url = @story.short_id_url

    @comments = @story.merged_comments.includes(:user,
      :story).arrange_for_user(@user)

    if params[:comment_short_id]
      @comments.each do |c,x|
        if c.short_id == params[:comment_short_id]
          c.highlighted = true
          break
        end
      end
    end

    respond_to do |format|
      format.html {
        @comment = @story.comments.build

        load_user_votes

        render :action => "show"
      }
      format.json {
        render :json => @story.as_json(:with_comments => @comments)
      }
    end
  end

  def undelete
    if !(@story.is_editable_by_user?(@user) &&
    @story.is_undeletable_by_user?(@user))
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user
    @story.save(:validate => false)

    redirect_to @story.comments_url
  end

  def update
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user

    if @story.url_is_editable_by_user?(@user)
      @story.attributes = story_params
    else
      @story.attributes = story_params.except(:url)
    end

    if @story.save
      return redirect_to @story.comments_url
    else
      return render :action => "edit"
    end
  end

  def unvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(0, story.id,
      nil, @user.id, nil)

    render :text => "ok"
  end

  def upvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(1, story.id,
      nil, @user.id, nil)

    render :text => "ok"
  end

  def downvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    if !Vote::STORY_REASONS[params[:reason]]
      return render :text => "invalid reason", :status => 400
    end

    if !@user.can_downvote?(story)
      return render :text => "not permitted to downvote", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(-1, story.id,
      nil, @user.id, params[:reason])

    render :text => "ok"
  end

  def hide
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(0, story.id,
      nil, @user.id, "H")

    render :text => "ok"
  end

  def unhide
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(0, story.id,
      nil, @user.id, nil)

    render :text => "ok"
  end

  def supporters
    if !(@story = find_story)
      return render :text => "can't find story", :status => 400
    end
    # todo abstract
    votes = Vote.where(story: @story)
    @users = []
    votes.each do |v| 
      @users.push(v.user) unless @users.include?(v.user)
    end
  end

private

  def story_params
    p = params.require(:story).permit(
      :title, :url, :description, :moderation_reason, :seen_previous,
      :merge_story_short_id, :tags_a => [],
    )

    if @user.is_moderator?
      p
    else
      p.except(:moderation_reason, :merge_story_short_id)
    end
  end

  def find_story
    story = Story.where(:short_id => params[:story_id]).first
    if @user && story
      story.vote = Vote.where(:user_id => @user.id,
        :story_id => story.id, :comment_id => nil).first.try(:vote)
    end

    story
  end

  def find_user_story
    if @user.is_moderator?
      @story = Story.where(:short_id => params[:story_id] || params[:id]).first
    else
      @story = Story.where(:user_id => @user.id, :short_id =>
        (params[:story_id] || params[:id])).first
    end

    if !@story
      flash[:error] = "Could not find story or you are not authorized " <<
        "to manage it."
      redirect_to "/"
      return false
    end
  end

  def load_user_votes
    if @user
      if v = Vote.where(:user_id => @user.id, :story_id => @story.id,
      :comment_id => nil).first
        @story.vote = v.vote
      end

      @votes = Vote.comment_votes_by_user_for_story_hash(@user.id, @story.id)
      @comments.each do |c|
        if @votes[c.id]
          c.current_vote = @votes[c.id]
        end
      end
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def show_guidelines?
    if !@user
      return true
    end

    if @user.stories_submitted_count <= 5
      return true
    end

    if Moderation.joins(:story).
    where("stories.user_id = ? AND moderations.created_at > ?", @user.id,
    5.days.ago).count > 0
      return true
    end

    false
  end
end

app/views/stories/_form.html.erb
<% if f.object.errors.count == 1 && f.object.already_posted_story %>
  <div class="flash-error">
  <h2>Error: This story was already submitted <%=
    time_ago_in_words(f.object.already_posted_story.created_at) %> ago</h2>
  <p>
  Please view the <a href="<%= f.object.already_posted_story.comments_url %>"
  target="_blank">previous discussion</a> for this story.
  </p>
  </div>
<% elsif f.object.errors.any? %>
  <%= error_messages_for f.object %>
<% elsif !f.object.errors.any? && f.object.already_posted_story %>
  <div class="flash-notice">
  <h2>Note: This story was already submitted <%=
    time_ago_in_words(f.object.already_posted_story.created_at) %> ago, but may
    be submitted again.</h2>
  <p>
  Please view the <a href="<%= f.object.already_posted_story.comments_url %>"
  target="_blank">previous discussion</a> for this story first.  If the content
  has changed or warrants new discussion, you may submit it again.
  </p>
  </div>

  <%= f.hidden_field :seen_previous %>
<% end %>

<div class="box">
  <div class="boxline">
  <% if f.object.url_is_editable_by_user?(@user) %>
    <%= f.label :url, "URL:", :class => "required" %>
    <%= f.text_field :url, :autocomplete => "off" %>
    <%= button_tag "Fetch Title", :id => "story_fetch_title",
      :type => "button" %>
  <% elsif !f.object.new_record? && !f.object.url.blank? %>
    <%= f.label :url, "URL:", :class => "required" %>
    <div class="d">
    <a href="<%= f.object.url %>"><%= f.object.url %></a>
    </div>
  <% end %>
  </div>

  <div class="boxline">
    <%= f.label :title, "Title:", :class => "required" %>
    <%= f.text_field :title, :maxlength => 100, :autocomplete => "off"  %>
  </div>

  <div class="boxline" style="margin-bottom: 2px;">
  <%= f.label :tags_a, "Tags:", :class => "required",
    :style => "line-height: 2.3em;" %>
  <%= f.select "tags_a", options_for_select(
    Tag.all_with_filtered_counts_for(@user).map{|t|
    [ "#{t.tag} - #{t.description}", t.tag, { "data-html" => raw("<strong>") +
      t.tag + raw("</strong> - ") + t.description.to_s +
      (t.filtered_count == 0 ? "" :
      raw(" <em>") + "#{t.filtered_count} user" +
      (t.filtered_count == 1 ? "" : "s") + " filtering" +
      raw("</em>")) } ]}, f.object.tags_a), {}, { :multiple => true } %>
  </div>

  <div class="boxline">
    <%= f.label :description, "Text:", :class => "required" %>
    <%= f.text_area :description, :rows => 15,
      :placeholder => "Optional when submitting a URL; please see guidelines",
      :autocomplete => "off" %>
  </div>

  <div class="boxline markdown_help_toggler">
    <a href="#" id="story_guidelines_toggler">
      Story submission guidelines
    </a>
    <div id="story_guidelines" style="<%= show_guidelines?? "" :
    "display: none;" %>">
      <div style="float: right;">
      <a href="javascript:window.location=%22<%= root_url %>stories/new?url=%22+encodeURIComponent(document.location)+%22&title=%22+encodeURIComponent(document.title)"
      style="border: 1px solid #ddd; padding: 0.5em; background-color:
      #f8f8f8; line-height: 1.5em; margin-left: 1em;">Submit to
      <%= Rails.application.name %></a>
      </div>
      <ul>

        <li><p>
        To be able to easily submit a page you're viewing in your browser
        to <%= Rails.application.name %>, drag the bookmarklet to the right
        to your bookmark bar.  You'll be taken to this page with the viewed
        page's URL and title.
        </p></li>

        <li><p>
        When submitting a URL, the text field is optional and should only
        be used when additional context or explanation of the URL is
        needed.  Commentary or opinion should be reserved for a comment,
        so that it can be voted on separately from the story.
        </p></li>

        <li><p>
        Do not editorialize story titles, but when the original story's
        title has no context or is unclear, please change it.  <strong>Please
        remove extraneous components from titles such as the name of the
        site or section.</strong>
        </p></li>

        <li><p>
        If no tags clearly apply to the story you are submitting, chances
        are it does not belong here.  Do not overreach with tags if they
        are not the primary focus of the story.
        </p></li>

        <li><p>
        When the story being submitted is more than a year or so old,
        please add the year the story was written to the post title in
        parentheses.
        </p></li>

      </ul>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $("#story_fetch_title").click(function() {
      Lobsters.fetchURLTitle($(this), $("#story_url"), $("#story_title"));
      return false;
    });
  });
</script>

app/views/stories/_listdetail.html.erb
<li id="story_<%= story.short_id %>" data-shortid="<%= story.short_id %>"
class="story <%= story.vote == 1 ? "upvoted" : "" %> <%= story.vote == -1 ?
"downvoted" : "" %> <%= story.vote == 0 ? "hidden" : "" %> <%= story.is_expired? ?
"expired" : "" %>">
<div class="story_liner">
  <div class="voters">
    <% if @user %>
      <a class="upvoter"></a>
    <% else %>
      <%= link_to "", login_url, :class => "upvoter" %>
    <% end %>
    <div class="score"><%= story.score %></div>
    <% if @user && @user.can_downvote?(story) %>
      <a class="downvoter"></a>
    <% else %>
      <span class="downvoter downvoter_stub"></span>
    <% end %>
  </div>
  <div class="details">
    <span class="link">
      <% if story.can_be_seen_by_user?(@user) %>
        <a href="<%= story.url_or_comments_url %>"><%= story.title %></a>
      <% end %>
      <% if story.is_gone? %>
        [Story removed by <%= story.is_moderated? ? "moderator" :
          "original submitter" %>]
      <% end %>
    </span>
    <% if story.can_be_seen_by_user?(@user) %>
      <span class="tags">
        <% story.taggings.sort_by{|t| t.tag.tag }.sort_by{|t|
        t.tag.tag == "pdf" ? -1 : 0 }.each do |tagging| %>
          <a href="<%= tag_url(tagging.tag.tag) %>"
            class="<%= tagging.tag.css_class %>"
            title="<%= tagging.tag.description %>"><%= tagging.tag.tag %></a>
        <% end %>
      </span>
      <span class="domain"><%= story.domain %></span>

      <% if defined?(single_story) && single_story %>
        <% story.merged_stories.each do |ms| %>
          <br>
          <span class="merge"></span>
          <span class="link">
            <a href="<%= ms.url_or_comments_url %>"><%= ms.title %></a>
          </span>
          <span class="tags">
            <% ms.taggings.sort_by{|t| t.tag.tag }.sort_by{|t|
            t.tag.tag == "pdf" ? -1 : 0 }.each do |tagging| %>
              <a href="<%= tag_url(tagging.tag.tag) %>"
                class="<%= tagging.tag.css_class %>"
                title="<%= tagging.tag.description %>"><%= tagging.tag.tag %></a>
            <% end %>
          </span>
          <span class="domain"><%= ms.domain %></span>
        <% end %>
      <% end %>
    <% end %>
    <div class="byline">
      <% if story.previewing %>
        by <a><%= story.user.username %></a>
        just now
      <% else %>
        by <a href="/u/<%= story.user.username %>"><%= story.user.username
          %></a> <%= raw(time_ago_in_words_label(story.created_at).
          gsub(/^about /, "")) %> ago

        <% if story.is_editable_by_user?(@user) %>
          |
          <%= link_to 'supporters', story_supporters_url(story) %>
          |
          <a href="<%= edit_story_url(story.short_id) %>">edit</a>

          <% if story.is_gone? && story.is_undeletable_by_user?(@user) %>
            |
            <%= link_to "undelete", story_undelete_url(story.short_id),
              :method => :post, :data => {
              :confirm => "Are you sure you want to undelete this story?" } %>
          <% elsif !story.is_gone? %>
            |
            <% if story.user_id != @user.try(:id) &&
            @user.try(:is_moderator?) %>
              <%= link_to "delete", story_url(story.short_id),
                :method => :delete, :class => "mod_story_link" %>
            <% else %>
              <%= link_to "delete", story_url(story.short_id),
                :method => :delete, :data => {
                :confirm => "Are you sure you want to delete this story?" } %>
            <% end %>
          <% end %>
        <% end %>
        <% if !story.is_gone? && @user %>
          <% if story.vote == 0 %>
            | <%= link_to "unhide", story_unhide_url(story.short_id),
              :class => "hider" %>
          <% else %>
            | <%= link_to "hide", story_hide_url(story.short_id),
              :class => "hider" %>
          <% end %>
          <% if defined?(single_story) && single_story && story.hider_count > 0 %>
            (hidden by <%= pluralize(story.hider_count, "user") %>)
          <% end %>
        <% end %>
        <% if !story.is_gone? && (@user || story.comments_count > 0) %>
          <span class="comments_label">
            |
            <a href="<%= story.comments_url %>"><%= story.comments_count == 0 ?
              "discuss" : "#{story.comments_count} comment" <<
              (story.comments_count == 1 ? "" : "s") %></a>
          </span>
        <% end %>

        <% if defined?(single_story) && single_story %>
          <% if story.downvotes > 0 %>
            | <%= story.vote_summary_for(@user).downcase %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="mobile_comments <%= story.comments_count == 0 ? "zero" : "" %>"
style="display: none;">
  <a href="<%= story.comments_url %>"><%= story.comments_count %></a>
</div>
</li>

app/views/stories/edit.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Edit Story
  </div>

  <%= form_for @story, :url => story_url(@story.short_id),
  :method => :put, :html => { :id => "edit_story" } do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f } %>

    <% if @user.is_moderator? && (@story.user_id != @user.id) %>
      <div class="box">
        <div class="boxline">
          <%= f.label :merge_story_short_id, "Merge Into:",
            :class => "required" %>
          <%= f.text_field :merge_story_short_id, :autocomplete => "off",
            :placeholder => "Short id of story into which this story " <<
            "be merged" %>
        </div>
        <div class="boxline">
          <%= f.label :moderation_reason, "Mod Reason:",
            :class => "required" %>
          <%= f.text_field :moderation_reason, :autocomplete => "off" %>
        </div>
      </div>
    <% end %>

    <p></p>

    <div class="box">
      <div class="boxline markdown_help_toggler">
        <div class="markdown_help_label">
          Markdown formatting available
        </div>

        <%= submit_tag "Save" %>
        &nbsp;or <a href="<%= story_url(@story.short_id) %>">cancel
          editing</a>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp",
          :locals => { :allow_images => true } %>
      </div>
    </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Submit a Story
  </div>

  <div id="story_holder">
    <%= form_for @story do |f| %>
      <%= render :partial => "stories/form", :locals => { :story => @story,
        :f => f } %>

      <p></p>

      <div class="box">
        <div class="boxline markdown_help_toggler">
          <div class="markdown_help_label">
            Markdown formatting available
          </div>

          <%= submit_tag "Submit" %>

          &nbsp;
          <button type="button" class="story-preview">Preview</button>

          <div style="clear: both;"></div>

          <%= render :partial => "global/markdownhelp",
            :locals => { :allow_images => true } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="story_preview">
  <% if @story.previewing && @story.valid? %>
    <%= render :template => "stories/show" %>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    <% if @story.previewing %>
      $("#story_tags_a").select2({
        formatSelection: function(what) {
          return what.id;
        }
      });
    <% else %>
      $("#story_url").focus();
    <% end %>
  });
</script>

app/views/stories/show.html.erb
<ol class="stories">
  <%= render :partial => "stories/listdetail",
    :locals => { :story => @story, :single_story => true } %>
</ol>

<div class="story_content">
  <% if @story.markeddown_description.present? %>
    <div class="story_text">
      <%= raw @story.markeddown_description %>
    </div>
  <% end %>
</div>

<% if !@story.previewing %>
  <ol class="comments comments1">
    <% if @user && !@story.is_gone? && !@story.previewing %>
      <li><%= render "comments/commentbox", :comment => @comment %></li>
    <% end %>

    <% comments_by_parent = @comments.group_by(&:parent_comment_id) %>
    <% subtree = comments_by_parent[nil] %>
    <% ancestors = [] %>

    <% while subtree %>
      <% if (comment = subtree.shift) %>
        <li>
        <%= render "comments/comment", :comment => comment,
          :show_story => (comment.story_id != @story.id),
          :was_merged => (comment.story_id != @story.id) %>

        <% if (children = comments_by_parent[comment.id]) %>
          <% ancestors << subtree %>
          <% subtree = children %>
          <ol class="comments">
        <% else %>
          <ol class="comments"></ol></li>
        <% end %>
      <% elsif (subtree = ancestors.pop) %>
        </ol></li>
      <% end %>
    <% end %>
  </ol>
<% end %>

app/views/stories/supporters.html.erb
<%= render :partial => 'stories/listdetail', locals: {story: @story} %>
<p>on Idealist.tips, 1 upvote == 1 supporter</p>
<p>below is everyone that supports this idea</p>
<table>
<tr>
  <th></th>
  <th>username</th>
  <th>email</th>
</tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username, user %> </td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>