config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index"#,
      # :protocol => (Rails.env == "production" ? "https://" : "http://")

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#new"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      get 'supporters'
    end
    post "/stories/fetch_url_title", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_filter :authenticate_user

  def index
    @cur_url = "/filters"
    @title = "Filtered Tags"

    @tags = Tag.active.all_with_story_counts_for(@user)

    if @user
      @filtered_tags = @user.tag_filter_tags.to_a
    else
      @filtered_tags = tags_filtered_by_cookie.to_a
    end
  end

  def update
    tags_param = params[:tags]
    new_tags = tags_param.blank? ? [] :
      Tag.active.where(:tag => tags_param).to_a
    new_tags.keep_if {|t| t.valid_for? @user }

    if @user
      @user.tag_filter_tags = new_tags
    else
      cookies.permanent[TAG_FILTER_COOKIE] = new_tags.map(&:tag).join(",")
    end

    flash[:success] = "Your filters have been updated."

    redirect_to filters_path
  end
end

app/views/filters/index.html.erb
<div class="box wide">
  <div class="legend">
    Filtered Tags
  </div>

  <p>
  To hide stories from the home page that have been tagged with certain tags,
  check them below.
  </p>

  <% if !@user %>
    <p>
    Since you are not logged in, your filters will be stored in a long-lasting
    browser cookie.  To permanently store your tag filters and have them work
    across browsers, <a href="/login">login</a> to your account.
    </p>
  <% end %>

  <%= form_tag "/filters", :method => :post do %>
    <table class="data zebra" cellspacing=0 width="75%">
    <tr>
      <th width="7%">Hide</th>
      <th width="13%">Tag</th>
      <th width="65%">Description</th>
      <th width="5%" style="text-align: right; padding-right: 1em;">Stories</th>
    </tr>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= check_box_tag "tags[]", tag.tag,
          @filtered_tags.include?(tag) %></td>
        <td><%= link_to tag.tag, tag_path(tag), :class => tag.css_class %></td>
        <td><%= tag.description %></td>
        <td style="text-align: right; padding-right: 1em;"><%=
          tag.stories_count %></td>
      </tr>
    <% end %>
    </table>
    <p>
    <%= submit_tag "Save Filters" %>
    </p>
  <% end %>
</div>